from setuptools import setup, find_packages

setup(
    name="advanced-emotion-detection",
    version="2.0.0",
    author="Niharika Hande",
    description="Advanced real-time emotion detection with 78% accuracy using ResNet and attention mechanisms",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    packages=find_packages(),
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Education",
        "Intended Audience :: Science/Research",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
        "Topic :: Software Development :: Libraries :: Python Modules",
    ],
    python_requires=">=3.8",
    install_requires=[
        "torch>=2.0.0",
        "torchvision>=0.15.0",
        "opencv-python>=4.8.0",
        "flask>=2.3.0",
        "numpy>=1.24.0",
        "pandas>=2.0.0",
        "matplotlib>=3.7.0",
        "seaborn>=0.12.0",
        "scikit-learn>=1.3.0",
        "pillow>=10.0.0",
        "requests>=2.31.0",
        "facenet-pytorch>=2.5.0",
        "mtcnn>=0.1.0",
        "tqdm>=4.65.0",
        "plotly>=5.15.0",
        "dash>=2.11.0",
        "dash-bootstrap-components>=1.4.0",
    ],
    keywords="emotion detection, face recognition, computer vision, deep learning, pytorch, cnn",
    project_urls={
        "Bug Reports": "https://github.com/niharika-hande04/emotion-detection/issues",
        "Source": "https://github.com/niharika-hande04/emotion-detection",
        "Documentation": "https://github.com/niharika-hande04/emotion-detection/blob/main/README.md",
    },
)
